name: Server — Deploy to Render
on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/server-render.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -s -X POST https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys             -H "Authorization: Bearer $RENDER_API_KEY"             -H "Content-Type: application/json"             -d '{}'
